version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  projetweb-frontend:
    image: projetweb-frontend
    container_name: projetweb-frontend
    ports:
      - "3000:3000"
    depends_on:
      - projetweb-backend

  projetweb-backend:
    image: projetweb-backend
    container_name: projetweb-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
